development:
  adapter: postgresql
  encoding: unicode
  database: library_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: library_test
  pool: 5
  username:
  password:
